name: Qiita Sync Check

on:
  schedule:
    - cron: "55 17 * * *"
  workflow_run:
    workflows: ["Qiita Sync"]
    types:
      - completed
  workflow_dispatch:

jobs:
  qiita_sync_check:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write  
    name: qiita-sync check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '20'
      - name: Install qiita-sync
        run: |
          python -m pip install qiita-sync
      - name: Run qiita-sync check
        run: |
          qiita_sync check . > ./qiita_sync_output.txt
          cat ./qiita_sync_output.txt
          [ ! -s "qiita_sync_output.txt" ] || exit 1
        env: 
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
